name: "Trigger Terraform Workflow"
on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  call-terraform:
    uses: Prathesh-Yadav/iac-vprofile/.github/workflows/terraform.yml@stage  # Use repo reference
    secrets: inherit  # Pass all secrets automatically
