name: "Trigger Terraform Workflow"
on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  call-terraform:
    uses: ./terraform/.github/workflows/terraform.yml  # Correct path to reusable workflow
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
        
